CREATE GROUP readwrite NOLOGIN;

GRANT CONNECT ON DATABASE crimes_db TO readwrite;
GRANT USAGE ON SCHEMA crimes TO readwrite;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crimes TO readwrite;

